os:
  - linux
  - osx

language: node_js

node_js:
  - node
  - 12
  - 10

cache:
  cargo: true
  yarn: true

before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  # Install NPM packages
  - node -v
  - npm -v
  - yarn install
script:
  # Run tests
  - yarn jest

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      os: linux
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm -g install @semantic-release/git semantic-release && semantic-release

